---
- name: do debian things on debian hosts
  include: "tasks-Debian.yml"
  when: ansible_os_family=='Debian'

- name: do redhat things on redhat hosts
  include: "tasks-RedHat.yml"
  when: ansible_os_family=='RedHat'

# Install required packages:
- pip: name={{item}} 
  with_items:
   - PyYAML 
   - Jinja2 
   - httplib2 
   - six
   - pycrypto

# ansible repo:
- name: get latest ansible git repo
  become: no
  git: >
    accept_hostkey=yes 
    repo=git://github.com/ansible/ansible 
    dest="{{ansible_dir}}"
