---
- name: add mongo repo from template
  template: src=mongodb-org-3.0.repo.j2 dest=/etc/yum.repos.d/mongodb-org-3.0.repo mode=0644
  
- name: install mongodb
  yum: name="{{item}}" state=present
  with_items:
  - mongodb-org

- name: start/enable service
  service: name=mongod state=started enabled=yes
