---
- name: clone repo
  git: 
    repo: "{{repo_source}}"
    dest: "{{source_dir}}/s3-backup"
    
- name: ensure ~/bin exists
  file:
    path: ~/bin
    state: directory

- name: create symlink
  file:
    src: "{{source_dir}}/s3-backup/s3-backup"
    dest: ~/bin/s3-backup
    state: link
