 - hosts: 192.168.1.69
   sudo: yes
   roles:
   - mongodb
   tasks:
   - name: install pip modules
     pip: name="{{item}}" state="present"
     with_items:
     - geopy
     #- geojson
     - pycountry
     - flask
     - pymongo
