---
- name: do debian things on debian hosts
  include: "tasks-Debian.yml"
  when: ansible_os_family=='Debian'

- name: do redhat things on redhat hosts
  include: "tasks-RedHat.yml"
  when: ansible_os_family=='RedHat'

- name: copy python test script
  become: no
  copy: src=test_hiredis.py dest=~ mode=0755

- name: clone rsyslog git repo
  become: no
  git:
    repo: https://github.com/rsyslog/rsyslog.git
    dest: ~/rsyslog
    version: v8-stable
    force: yes

- name: clone my fork
  become: no
  git:
    repo: https://github.com/jaymell/rsyslog.git
    version: fixHiredisCheck
    dest: ~/jsyslog
    force: yes

- name: create conf.d
  file: name=/etc/rsyslog.d state=directory mode=0755

- name: test rsyslog config
  copy: src="{{item.name}}" dest="{{item.dest}}" mode=0644 force=yes
  with_items:
  - { name: files/rsyslog.conf, dest: /etc/rsyslog.conf }
  - { name: files/22-redis.conf, dest: /etc/rsyslog.d/22-redis.conf }

- name: put syntax for check in file
  become: no
  copy: content="{{item}}" dest=~/check-config-syntax
  with_items: "autoreconf -fiv\n./configure --enable-omhiredis\nmake\nsudo make install\n/usr/local/sbin/rsyslogd -N1\n\n "

- name: install redis python module
  pip: name=redis

- name: delete any previous stuff
  become: no
  command: bash -c "cd ~/{{repo_dir}} && make dist clean"
  ignore_errors: True

- name: autoreconf
  become: no
  command: bash -c "cd ~/{{repo_dir}} && autoreconf -fiv" 

- name: configure
  become: no
  command: bash -c "cd ~/{{repo_dir}} && ./configure --enable-omhiredis=yes"
  #command: bash -c "cd ~/{{repo_dir}} && ./configure"

- name: make
  become: no
  command: bash -c "cd ~/{{repo_dir}} && make"

- name: install
  command: bash -c "cd /home/{{ansible_user}}/{{repo_dir}} && make install"

- name: kill any running rsyslog
  command: bash -c "pkill rsyslogd"
  ignore_errors: True

- name: start rsyslog
  command: bash -c "/usr/local/sbin/rsyslogd" 

- name: test
  become: no
  command: bash -c "./test_hiredis.py"
