---
  - name: remove stock rsyslog
    apt:
      name: rsyslog
      state: absent
  - name: add rsyslog repo key
    apt_key: keyserver=keys.gnupg.net id=AEF0CF8E
  - name: add rsyslog repos
    apt_repository: repo={{item}} state=present
    with_items:
    - 'deb http://debian.adiscon.com/v8-stable wheezy/'
    - 'deb-src http://debian.adiscon.com/v8-stable wheezy/'
  - name: install packages
    apt: name="{{item}}" state=present 
    ### this list can be cleaned up big time: ####
    with_items:
    - pkg-config
    - git
    - automake
    - libtool
#    - zlib-dev
    - uuid
    - libgcrypt-dev
    - flex
    - bison
    - uuid-dev
#    - libuuid-dev
#    - liblogging-dev
    - liblogging-stdlog-dev
#    - json-c-dev
    - libjson-c-dev
#    - hiredis-dev
    - libhiredis-dev
    - python-docutils
    - python-sphinx
#    - openssl-dev
#    - libcurl-dev
#    - libcurl4-openssl-dev
#    - libcurl4-gnutls-dev
#    - gnutls-dev
#    - mysql-dev
#    - postgresql-dev
#    - libdbi-dbd-mysql
    - libdbi-dev
#    - net-snmp-dev
    - redis-server
    - libfastjson-dev
    - python-pip

  - name: start redis 
    service: name=redis-server state=started enabled=yes


