- name: for debian hosts
  include: "tasks-Debian.yml"
  when: ansible_os_family=='Debian'

- name: for RedHat / CentOS hosts
  include: "tasks-RedHat.yml"
  when: ansible_os_family=='RedHat'

- name: install some basic tools globally
  npm: name={{item}} global=yes state=latest
  with_items:
    - nodemon
    - node-inspector

