- name: install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=installed

- name: install important stuff
  yum: name={{item}} state=present
  with_items:
  - ruby
#  - rubygems
  - zlib
  - libvirt
  - libvirt-devel

#- name: install vagrant gem
#  gem: name=vagrant state=present

