---
- name: ensure gopath exists
  file:
    path: "{{go_path}}/src"
    state: directory
    recurse: yes
  become: no

- debug: var=go_path

- name: install camlistore manually
  shell: cd ~/go/src && git clone https://camlistore.googlesource.com/camlistore && cd camlistore && go run make.go
#  - shell: go install github.com/camlistore/camlistore/...
  become: no
  args:
    creates: "{{go_path}}/src/camlistore"

- name: initialize camlistore db
  shell: cd ~/go/src/camlistore && bin/camtool dbinit -password "{{mysql_root_pass}}" --dbname camlistore -wipe
#  - shell: camtool dbinit -password "{{mysql_root_pass}}" --dbname camlistore
  become: no

- name: copy camlistore unit file
  template:
    src: camlistore.service.j2
    dest: /etc/systemd/system/camlistore.service

- name: ensure camlistore dir exists
  file:
    path: "{{home_dir}}/.config/camlistore"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0700
    recurse: yes

- name: copy gpg key
  copy:
    src: "{{gpg_src}}"
    dest: "{{home_dir}}/.config/camlistore/identity-secring.gpg"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0600

- name: get fingerprint from gpg key
  shell: gpg --with-fingerprint "{{gpg_dest}}" | grep fingerprint | awk '{print $(NF-1) $NF}'
  register: gpg_fingerprint_raw

- debug: var=gpg_fingerprint_raw

- name: register fingerprint # used in server-config.json
  set_fact:
    gpg_fingerprint: "{{ gpg_fingerprint_raw.stdout_lines[0] }}"

- name: copy server s3 config
  template:
    src: server-config-s3.json.j2
    dest: "{{home_dir}}/.config/camlistore/server-config.json"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0600
  when: use_s3 == "yes"

- name: copy server local config
  template:
    src: server-config-local.json.j2
    dest: "{{home_dir}}/.config/camlistore/server-config.json"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0600
  when: use_s3 == "no"

- name: enable/start camlistore service
  systemd:
    daemon_reload: yes
    name: camlistore
    state: started
    enabled: yes

