---
app: default
instance_type: t2.micro
# ubuntu -- would be better to make sure this is latest with ec2_ami_find:
image_id: ami-fce3c696
count: 1 # change for multiple instances
security_groups: ["ssh", "outbound"]
vpc_name: default
user_data: ""
inventory_group: throw_away
key_name: throw_away
# overwrite this if you don't want cleanup job to delete it:
tag: { type: throw_away, Name: "{{app}}-throw_away" }
