- name: enable Docker repo
  apt_repository: repo="deb https://apt.dockerproject.org/repo debian-{{ansible_lsb.codename}} main"

- name: add repo key
  apt_key: keyserver="hkp://pgp.mit.edu:80" id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: install necessary packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - docker-engine

