- name: add repo key
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id="58118E89F3A912897C070ADBF76221572C52609D" state=present

# necessary to specify http instead of https on repo, despite docker webpage
- name: enable Docker repo
  apt_repository: repo="deb http://apt.dockerproject.org/repo ubuntu-{{ansible_distribution_release}} main"

- name: purge unnecessary repo
  apt: name=lxc-docker state=absent purge=yes

- name: install necessary packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - docker-engine

