# note: apcupsd-cgi package puts files into
# /usr/lib/cgi-bin, which may require
# configuration changes for apache, etc.,
# to get content served out:
- name: install apcupsd -- Debian
  apt: name=apcupsd state=latest
  with_items:
  - apcupsd
  - apcupsd-cgi
  when: ansible_os_family == 'Debian'

- name: copy config file
  template: src=apcupsd.conf.j2 dest=/etc/apcupsd/apcupsd.conf mode=0644

- name: change /etc/default/apcupsd
  lineinfile: dest=/etc/default/apcupsd regexp='ISCONFIGURED.*$' line='ISCONFIGURED=yes'

- name: enable / restart service
  service: name=apcupsd state=restarted enabled=yes
