 - hosts: localhost
   become: yes
   vars: 
     tlpi_url: http://man7.org/tlpi/code/download
     tlpi_gz: tlpi-150424-dist.tar.gz
   roles:
   - linux_source
   - c_compiler
   tasks:
   - name: install coreutils source to /usr/src
     command: chdir=/usr/src /usr/bin/apt-get source coreutils
   - name: download _the_linux_programming_interface_ source code
     get_url: url="{{tlpi_url}}/{{tlpi_gz}}" dest=/tmp
   - name: extract tlpi source
     unarchive: src="/tmp/{{tlpi_gz}}" dest=/usr/src
