---
# provision / ensure aws environment
- name: provision camlistore aws instance
  hosts: localhost
  vars:
    # overwrite these on cli via --extra-vars if needed:
    region: us-east-1
    ami_id: ami-ddf13fb0
    app: camlistore
    # can this be dynamic based on below?
    security_groups: ["ssh", "http", "outbound", "camlistore"]
    tag: { type: camlistore, Name: "{{app}}" }

  pre_tasks:
  - include: tasks/aws_inbound_sg.yml 
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 22
      sg_name: 'ssh'
  - include: tasks/aws_inbound_sg.yml
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 80
      sg_name: 'http'
  - include: tasks/aws_inbound_sg.yml
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 3179
      sg_name: 'camlistore'

  - include: tasks/aws_outbound_sg.yml
    vars:
      outbound_ip_range: 0.0.0.0/0
      proto: all
      sg_name: 'outbound'

  - include: tasks/create_ec2_key.yml
    vars:
      key_name: camlistore

  roles:
  - { role: aws_ec2, image_id: "{{ami_id}}", key_name: camlistore }

  tasks:
  - name: add instance to in-memory inventory so we can run plays on it later
    add_host:
     hostname: "{{item.public_ip}}"
     groups: camlistore
    with_items: "{{ec2_instance.tagged_instances}}"

  - name: wait for instance accessible
    wait_for:
     host: "{{item.public_ip}}"
     port: 22
     search_regex: "OpenSSH"
    with_items: "{{ec2_instance.tagged_instances}}"

# pre-play -- install python 2
- name: install python2
  hosts: camlistore
  gather_facts: no
  remote_user: ubuntu
  tasks:
  - name: 'install python2'
    raw: sudo apt-get update && sudo apt-get -y install python-simplejson

# actually ssh to a server and do stuff
# pass "mysql_root_pass" as an extra var on command line
- name: provision instance
  hosts: camlistore
  become: yes
  remote_user: ubuntu

  roles:
#  - golang-download
  - role: bennojoy-mysql # bennojoy's awesome mysql provisioning role, forked @ https://github.com/jaymell/mysql
    mysql_root_db_pass: "{{mysql_root_pass}}" 
  - role: camlistore

