---
# actually ssh to a server and do stuff
# pass "mysql_root_pass" as an extra var on command line
- name: provision instance
  hosts: aws_camlistore
  become: yes
  remote_user: ubuntu

  roles:
  - golang-download
#  - role: bennojoy-mysql # bennojoy's awesome mysql provisioning role, forked @ https://github.com/jaymell/mysql
#    mysql_root_db_pass: "{{mysql_root_pass}}" 
  - role: camlistore

