---
- name: provision instance
  hosts: ubu-phys-00
  become: yes

  roles:
#  - golang-download
#  - role: bennojoy-mysql # bennojoy's awesome mysql provisioning role, forked @ https://github.com/jaymell/mysql
#    mysql_root_db_pass: "{{mysql_root_pass}}" 
  - role: camlistore

