---
#aws ec2 describe-images --filters Name=owner-id,Values=099720109477
- name: provision camlistore aws instance
  hosts: localhost
  vars:
    region: us-east-1
    ami_id: ami-ddf13fb0
    app: ubuntu-16
    security_groups: ["ssh", "http", "outbound"]

  pre_tasks:
  - include: aws_inbound_sg.yml 
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 22
      sg_name: 'ssh'
  - include: aws_inbound_sg.yml
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 80
      sg_name: 'http'
  - include: aws_outbound_sg.yml
    vars:
      outbound_ip_range: 0.0.0.0/0
      proto: all
      sg_name: 'outbound'

  roles:
  - { role: aws_throw_away, image_id: "{{ami_id}}" }


  tasks:
  - name: add instance to inventory
    add_host:
     hostname: "{{item.public_ip}}"
     groups: camlistore
    with_items: "{{throw_away.tagged_instances}}"

  - name: wait for instance accessible
    wait_for:
     host: "{{item.public_ip}}"
     port: 22
     search_regex: "OpenSSH"
    with_items: "{{throw_away.tagged_instances}}"

- name: install python2
  hosts: camlistore
  gather_facts: no
  remote_user: ubuntu
  tasks:
  - name: 'install python2'
    raw: sudo apt-get update && sudo apt-get -y install python-simplejson

- name: provision instance
  hosts: camlistore
  become: yes
  remote_user: ubuntu
  roles:
  - golang-download
  tasks:
  - shell: cd ~/go/src && git clone https://camlistore.googlesource.com/camlistore && cd camlistore && go run make.go
    become: ubuntu

