---
#aws ec2 describe-images --filters Name=owner-id,Values=099720109477
- name: provision throwaway
  hosts: localhost
  vars:
    region: us-east-1

  tasks:
  - name: ec2 facts
    ec2_remote_facts:
      region: "{{region}}"
      filters:
        "tag:type": throw_away
    register: ec2_info

  - debug: var=ec2_info


  - name: throw away
    ec2:
      state: absent
      instance_ids:
      - "{{item.id}}"
      instance_tags: { type: throw_away }
      region: "{{region}}"
    with_items: ec2_info.instances
      
  
