---
# example command line:
#ansible-playbook -i playbooks/hosts playbooks/deploy-photo_mapper.yml  --private-key=~/.ssh/photo_mapper.pem 
- name: provision SGs and instance
  hosts: localhost
  vars:
    region: us-east-1
    instance_type: t2.micro
    instance_profile: photo_mapper
    key_name: photo_mapper
    # ubuntu
    mongodb_image: ami-fce3c696
    mongodb_ip: 172.31.51.90
    # latest aws ecs-optimized for docker hosts
    docker_image: ami-2b3b6041
    mongodb_count: 1
    docker_count: 3
    ecs_cluster: pm_docker
  tasks:
  - name: create ssh security group
    ec2_group:
     name: ssh
     region: "{{region}}"
     description: allow inbound ssh
     rules:
     - proto: tcp
       from_port: 22
       to_port: 22
       cidr_ip: 0.0.0.0/0
  - name: create http security group
    ec2_group:
     name: http
     region: "{{region}}"
     description: allow inbound http
     rules:
     - proto: tcp
       from_port: 80
       to_port: 80
       cidr_ip: 0.0.0.0/0
  - name: create mongodb security group
    ec2_group:
     name: mongodb
     region: "{{region}}"
     description: allow inbound mongodb connectivity
     rules:
     - proto: tcp
       from_port: 27017
       to_port: 27017
       # should be smarter about this -- no
       # no reason that ANYTHING outside of vpc
       # needs to access this:
       cidr_ip: 0.0.0.0/0
  - name: create outbound security group
    ec2_group:
     name: outbound
     region: "{{region}}"
     description: allow outbound connections
     rules_egress:
     - proto: all
       cidr_ip: 0.0.0.0/0

  - name: create mongodb instance
    ec2:
     image: "{{mongodb_image}}"
     region: "{{region}}"
     instance_type: "{{instance_type}}"
     instance_profile_name: "{{instance_profile}}"
     instance_tags: { type: pm_mongodb, Name: pm_mongodb }
     assign_public_ip: no
     private_ip: "{{mongodb_ip}}"
     key_name: "{{key_name}}"
     count_tag: { type: pm_mongodb }
     exact_count: "{{mongodb_count}}"
     group: [ssh, outbound, mongodb]
     wait: yes
    register: mongodb_ct

  - name: add instance to inventory / mongodb_aws group
    add_host:
     hostname: "{{item.private_ip}}"
     groups: mongodb_aws
    with_items: mongodb_ct.tagged_instances

  # this doesn't work very well, given that aws
  # doesn't let you modify existing launch configs:
  - name: ensure docker launch config 
    ec2_lc: 
     name: pm_docker
     region: "{{region}}"
     image_id: "{{docker_image}}"
     # this sucks, but aws requires IDs here, not names:
     security_groups: [sg-43ccb73a, sg-72793f0b, sg-86783eff]
     key_name: "{{key_name}}"
     instance_type: "{{instance_type}}"
     instance_profile_name: "{{instance_profile}}"
     user_data: "#!/bin/bash\necho ECS_CLUSTER={{ecs_cluster}} >> /etc/ecs/ecs.config\n"
    register: docker_lc
    tags:
    - lc

  - name: ensure auto-scaling group
    ec2_asg:
     name: pm_docker
     region: "{{region}}"
     launch_config_name: pm_docker
     min_size: 3
     max_size: 3
    tags:
    - asg
   
  - name: wait for mongo instance accessible
    wait_for:
     host: "{{item.private_ip}}"
     port: 22
     search_regex: "OpenSSH"
    with_items: mongodb_ct.tagged_instances

# mongo provision play
- name: mongodb on mongodb_ct.tagged_instances
  vars:
    mongodb_bind_address: 0.0.0.0
  hosts: mongodb_aws
  remote_user: ubuntu
  become: yes
  roles:
  - mongodb
