--- 
- name: provision throwaway
  hosts: localhost
  vars:
    region: us-east-1
    ami_id: ami-ddf13fb0
    app: ubuntu-16
    user_name: ubuntu


  roles:
  - { role: aws_inbound_sg, port_number: 22, sg_name: 'ssh' }
  - { role: aws_outbound_sg } # default unrestricted
  - { role: aws_ec2, image_id: "{{ami_id}}" }

  tasks: 
  - name: add instance to inventory
    add_host:
     hostname: "{{item.public_ip}}"
     groups: snapd
    with_items: "{{throw_away.tagged_instances}}"

  - name: wait for instance accessible
    wait_for:
     host: "{{item.public_ip}}"
     port: 22
     search_regex: "OpenSSH"
    with_items: "{{throw_away.tagged_instances}}"

- name: install python2
  hosts: snapd
  gather_facts: no
  remote_user: ubuntu
  tasks:
  - name: 'install python2'
    raw: sudo apt-get update && sudo apt-get -y install python-simplejson

- name: provision instance
  hosts: snapd
  become: yes
  remote_user: ubuntu
  roles: 
  - snapd-dev
  - { role: git-config, repo: /home/ubuntu/go/src/github.com/snapcore/snapd, user: ubuntu }
  tasks:
  - name: bashrc helpers
    blockinfile:
      dest: /home/ubuntu/.bashrc
      block: |
        function snapd() {
          case $1 in
            start)
              sudo systemctl stop snapd.service snapd.socket
              sudo /lib/systemd/systemd-activate -E SNAPD_DEBUG=1 -l /run/snapd.socket $GOPATH/bin/snapd &
              sleep 2
              sudo chmod 666 /run/snapd.socket
              ;;
            build)
              go clean
              go install github.com/snapcore/snapd/...
              ;;
          esac
        }

