--- 
# two separate playbooks b/c no python2 in ubuntu 16 by default;
# "gather_facts: no" essential to allow its raw installation

- name: provision throwaway
  hosts: ubu-phys-00
  become: yes
  gather_facts: no
  tasks:
  - name: install python2
    raw: sudo apt-get update && sudo apt-get -y install python-simplejson

# separate play
- name: provision throwaway
  hosts: ubu-phys-00
  become: yes
  vars:
    user_name: james
  roles: 
  - snapd-dev
  - { role: git-config, repo: "/home/{{user_name}}/go/src/github.com/snapcore/snapd" }

  tasks:
  - name: bashrc helpers
    blockinfile:
      dest: /home/ubuntu/.bashrc
      block: |
        function snapd() {
          case $1 in
            start)
              sudo systemctl stop snapd.service snapd.socket
              sudo /lib/systemd/systemd-activate -E SNAPD_DEBUG=1 -l /run/snapd.socket $GOPATH/bin/snapd &
              sleep 2
              sudo chmod 666 /run/snapd.socket
              ;;
            build)
              go clean
              go install github.com/snapcore/snapd/...
              ;;
          esac
        }

