---
#aws ec2 describe-images --filters Name=owner-id,Values=099720109477
- name: provision throwaway
  hosts: localhost
  vars:
    region: us-east-1
    app: ecs-throwaway
    security_groups: ["ssh", "http", "outbound"]
    inventory_group: throw_away
    instance_type: t2.micro
    key_name: throw_away
    # ubuntu -- would be better to make sure this is latest with ec2_ami_find:
    image_id: ami-6bb2d67c
    tag: { type: throw_away, Name: "{{app}}-throw_away" }
    count: 1
    vpc_name: default
    user_data: ""
    instance_profile_name: "InstanceProfile-InstanceProfile-FT269ECL4E0I"
  pre_tasks:
  - include: aws_inbound_sg.yml 
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 22
      sg_name: 'ssh'
  - include: aws_inbound_sg.yml
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 80
      sg_name: 'http'
  - include: aws_outbound_sg.yml
    vars:
      outbound_ip_range: 0.0.0.0/0
      proto: all
      sg_name: 'outbound'
  tasks:
  - name: create throw_away instance
    ec2:
     image: "{{image_id}}"
     region: "{{region}}"
     instance_type: "{{instance_type}}"
     instance_tags: "{{tag}}"
     key_name: "{{key_name}}"
     count_tag: "{{tag}}"
     exact_count: "{{count}}"
     user_data: "{{user_data}}"
     group: "{{security_groups}}"
     instance_profile_name: "{{instance_profile_name}}"
     wait: yes
    register: throw_away
  
  - name: add instance(s) to inventory
    add_host:
     hostname: "{{item.public_ip}}"
     groups: "{{inventory_group}}"
    with_items: throw_away.tagged_instances
  
  - name: wait for instance(s) accessible
    wait_for:
     host: "{{item.public_ip}}"
     port: 22
     search_regex: "OpenSSH"
    with_items: throw_away.tagged_instances

