---
- name: provision throwaway
  hosts: localhost
  vars:
    region: us-east-1
    count: 1
    tag: { Name: centos6_throwaway }
  roles:
  - { role: aws_inbound_sg, port_number: 22, sg_name: 'ssh' }
  - { role: aws_outbound_sg } # default unrestricted
  - { role: aws_ec2, image_id: ami-57cd8732, vpc_name: "testin}" }
