---
#aws ec2 describe-images --filters Name=owner-id,Values=099720109477
- name: provision throwaway
  hosts: localhost
  vars:
    region: us-east-1
    ami_id: ami-ddf13fb0
    app: ubuntu-16
    security_groups: ["ssh", "http", "outbound"]

  pre_tasks:
  - include: aws_inbound_sg.yml 
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 22
      sg_name: 'ssh'
  - include: aws_inbound_sg.yml
    vars:
      source_ip_range: 0.0.0.0/0
      proto: tcp
      port_number: 80
      sg_name: 'http'
  - include: aws_outbound_sg.yml
    vars:
      outbound_ip_range: 0.0.0.0/0
      proto: all
      sg_name: 'outbound'

  roles:
  - { role: aws_ec2, image_id: "{{ami_id}}" }
