---
- name: provision throwaway
  hosts: localhost
  vars:
    region: us-east-1
  roles:
  - { role: aws_inbound_sg, port_number: 22, sg_name: 'ssh' }
  - { role: aws_outbound_sg } # default unrestricted
  - { role: aws_throw_away, image_id: ami-60b6c60a, vpc_name: "testin}" }
