 - hosts: netbook
   sudo: yes
   #roles:
   #- mongodb
   tasks:
   - name: install pip modules
     pip: name="{{item}}" state="present"
     with_items:
     - flask
     - pyephem
     - pymongo
   #- name: make sure unzip is installed
   #  apt: name="unzip" state="present"

